<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.w3.org/1999/xhtml" xpath-default-namespace="http://www.w3.org/1999/xhtml"
    xmlns:epub="http://www.idpf.org/2007/ops" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:pfn="http://pugo.co/functions" exclude-result-prefixes="xs" version="2.0">

    <xsl:variable name="title" select="(/html/body/*[tokenize(@class, ' ') = 'title'])[1]//text()"/>

    <xsl:param name="pub-language" select="'en'"/>
    <xsl:param name="bookid" select="concat('http://pugo.co/', replace($title, ' ', ''))"/>
    <xsl:param name="grouping-level" as="xs:integer" select="3"/>


    <!-- 
        Creating hierarchical structure from flat html to a temporary variable
        By default this will group into chapters and subchapters starting with each h1, h2 and h3
    -->
    <xsl:variable name="chapters">
        <!-- 
            h1
        -->
        <xsl:for-each-group select="/html/body/*[not(tokenize(@class, ' ') = 'title')]"
            group-starting-with="h1[.//text()]">
            <chapter>
                <xsl:copy-of select="current-group()[1]/@*"/>
                <section
                    epub:type="{if (current-group()[1]/self::h1) then 'chapter' else 'preface'}">
                    <xsl:choose>
                        <!-- 
                            h2
                        -->
                        <xsl:when test="$grouping-level >= 2">
                            <xsl:variable name="current-group">
                                <xsl:copy-of select="current-group()"/>
                            </xsl:variable>
                            <xsl:copy-of
                                select="$current-group/*[not(self::h2 | preceding-sibling::h2)]"/>
                            <xsl:for-each-group
                                select="$current-group/*[self::h2 | preceding-sibling::h2]"
                                group-starting-with="h2[.//text()]">
                                <section epub:type="subchapter">
                                    <xsl:choose>
                                        <!-- 
                                            h3
                                        -->
                                        <xsl:when test="$grouping-level >= 3">
                                            <xsl:variable name="current-group">
                                                <xsl:copy-of select="current-group()"/>
                                            </xsl:variable>
                                            <xsl:copy-of
                                                select="$current-group/*[not(self::h3 | preceding-sibling::h3)]"/>
                                            <xsl:for-each-group
                                                select="$current-group/*[self::h3 | preceding-sibling::h3]"
                                                group-starting-with="h3[.//text()]">
                                                <section epub:type="subchapter">
                                                  <xsl:copy-of select="current-group()"/>
                                                </section>
                                            </xsl:for-each-group>
                                        </xsl:when>
                                        <xsl:otherwise>
                                            <xsl:copy-of select="current-group()"/>
                                        </xsl:otherwise>
                                    </xsl:choose>
                                </section>
                            </xsl:for-each-group>
                        </xsl:when>
                        <xsl:otherwise>
                            <xsl:copy-of select="current-group()"/>
                        </xsl:otherwise>
                    </xsl:choose>
                </section>
            </chapter>
        </xsl:for-each-group>
    </xsl:variable>


    <!-- main template -->
    <xsl:template match="/">

        <xsl:variable name="default_title" select="'ePub generated by Pugo.co'"/>
        <xsl:variable name="title"
            select="
                if ($title != '') then
                    $title
                else
                    $default_title"/>

        <!-- mimetype -->
        <xsl:result-document href="mimetype" method="text"
            >application/epub+zip</xsl:result-document>

        <!-- container -->
        <xsl:result-document href="META-INF/container.xml">
            <container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0">
                <rootfiles>
                    <rootfile full-path="EPUB/content.opf"
                        media-type="application/oebps-package+xml"/>
                </rootfiles>
            </container>
        </xsl:result-document>

        <!-- content.opf -->
        <xsl:result-document href="EPUB/content.opf">
            <package xmlns="http://www.idpf.org/2007/opf"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dcterms="http://purl.org/dc/terms/" version="3.0" xml:lang="en"
                unique-identifier="bookid">
                <metadata>
                    <dc:title>
                        <xsl:value-of select="$title"/>
                    </dc:title>
                    <dc:language id="pub-language">
                        <xsl:value-of select="$pub-language"/>
                    </dc:language>
                    <dc:identifier id="bookid">
                        <xsl:value-of select="$bookid"/>
                    </dc:identifier>
                    <meta property="dcterms:modified">
                        <xsl:value-of
                            select="format-dateTime(current-dateTime(), '[Y0001]-[M01]-[D01]T[H]:[m]:[s]Z')"
                        />
                    </meta>
                </metadata>
                <manifest>
                    <!--<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>-->
                    <item id="htmltoc" properties="nav" media-type="application/xhtml+xml"
                        href="toc.xhtml"/>
                    <item id="front_cover" href="front-cover.xhtml"
                        media-type="application/xhtml+xml"/>
                    <xsl:for-each select="$chapters/*">
                        <item id="{pfn:generateItemID(section)}"
                            href="{pfn:generateFileName(section)}.xhtml"
                            media-type="application/xhtml+xml"/>
                    </xsl:for-each>
                    <!--<xsl:for-each-group select="$chapters//img" group-by="@src">
                        <xsl:variable name="name"
                            select="
                                if (@alt = '') then
                                    concat('image', count(preceding::img[@alt = '']) + 1, '.png')
                                else
                                    @alt"/>
                        <item id="{$name}" href="images/{$name}"
                            media-type="image/{replace(tokenize($name,'\.')[last()],'jpg','jpeg','i')}"
                        />
                    </xsl:for-each-group>-->
                    <item id="style" href="stylesheet.css" media-type="text/css"/>
                </manifest>
                <spine>
                    <itemref idref="front_cover"/>
                    <xsl:for-each select="$chapters/*">
                        <itemref idref="{pfn:generateItemID(section)}"/>
                    </xsl:for-each>
                </spine>
            </package>
        </xsl:result-document>

        <!-- front-cover.xhtml -->
        <xsl:result-document href="EPUB/front-cover.xhtml" method="xhtml">
            <html xmlns="http://www.w3.org/1999/xhtml">
                <head>
                    <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
                    <title>
                        <xsl:value-of select="$title"/>
                    </title>
                </head>
                <body>
                    <h1>
                        <xsl:value-of select="$title"/>
                    </h1>
                    <h2>Created with pugo.co</h2>
                    <xsl:if test="$title = $default_title">
                        <p>No Title was found in your Google Doc, please set a Heading as
                            'Title'.</p>
                    </xsl:if>
                </body>
            </html>
        </xsl:result-document>

        <!-- stylesheet.css -->
        <xsl:result-document href="EPUB/stylesheet.css" method="text">
            <xsl:variable name="regex">(.*?)\{(.*?)\}</xsl:variable>
            <xsl:analyze-string select="/html/head/style/text()" regex="{$regex}">
                <xsl:matching-substring>
                    <xsl:if test="not(matches(regex-group(1), 'import'))">
                        <xsl:value-of select="regex-group(1)"/>
                        <xsl:text> {&#10;</xsl:text>
                        <xsl:for-each select="tokenize(regex-group(2), ';')">
                            <xsl:if test="not(matches(., 'direction:'))">
                                <xsl:text>    </xsl:text>
                                <xsl:value-of select="."/>
                                <xsl:text>;&#10;</xsl:text>
                            </xsl:if>
                        </xsl:for-each>
                        <xsl:text>}&#10;</xsl:text>
                    </xsl:if>
                </xsl:matching-substring>
            </xsl:analyze-string>
        </xsl:result-document>


        <!-- chapters -->
        <xsl:apply-templates select="$chapters/*"/>


        <!-- toc.ncx 
            
            toc.ncx is needed for epub 2.0 compatibility
            there could be problems with a nested structure and certain devices:
            http://epubsecrets.com/nesting-your-toc-in-the-ncx-file-and-the-nookkindle-workaround.php
            
            
        <xsl:result-document href="EPUB/toc.ncx">
            <ncx xmlns:ncx="http://www.daisy.org/z3986/2005/ncx/"
                xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1" xml:lang="en">
                <head>
                    <meta name="dtb:uid" content="http://example.org/dummy/URIstub/"/>
                    <meta name="dtb:depth" content="1"/>
                    <meta name="dtb:totalPageCount" content="0"/>
                    <meta name="dtb:maxPageNumber" content="0"/>
                </head>
                <docTitle>
                    <text/>
                </docTitle>
                <navMap>
                    <navPoint id="front_cover" playOrder="1">
                        <navLabel>
                            <text>
                                <xsl:value-of select="$title"/>
                            </text>
                        </navLabel>
                        <content src="front-cover.xhtml"/>
                    </navPoint>
                    <xsl:for-each select="$chapters/*">
                        <navPoint id="chapter{position()}" playOrder="{position()+1}">
                            <navLabel>
                                <text>
                                    <xsl:value-of select="h1"/>
                                </text>
                            </navLabel>
                            <content src="chapter{position()}.xhtml"/>
                        </navPoint>
                    </xsl:for-each>
                </navMap>
            </ncx>
        </xsl:result-document>-->

        <!-- toc.xhtml -->
        <xsl:result-document href="EPUB/toc.xhtml" method="xhtml">
            <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
                <head>
                    <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
                </head>
                <body>
                    <nav epub:type="toc" id="toc">
                        <ol>
                            <li>
                                <a href="front-cover.xhtml">
                                    <xsl:value-of select="$title"/>
                                </a>
                            </li>
                            <xsl:apply-templates select="$chapters/*" mode="toc"/>
                        </ol>
                    </nav>
                </body>
            </html>
        </xsl:result-document>
    </xsl:template>

    <xsl:template match="chapter">
        <xsl:result-document href="EPUB/{pfn:generateFileName(section)}.xhtml" method="xhtml">
            <html xmlns="http://www.w3.org/1999/xhtml">
                <head>
                    <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
                    <title>
                        <xsl:value-of select="section/h1"/>
                    </title>
                </head>
                <body>
                    <xsl:apply-templates select="section"/>
                </body>
            </html>
        </xsl:result-document>
    </xsl:template>



    <xsl:template match="section">
        <section>
            <xsl:copy-of select="@*"/>
            <xsl:attribute name="title" select="h1 | h2 | h3"/>
            <xsl:attribute name="id" select="pfn:generateChapterID(.)"/>
            <xsl:apply-templates select="*"/>
        </section>
    </xsl:template>




    <xsl:template match="section" mode="toc">
        <xsl:variable name="fileName" select="pfn:generateFileName(ancestor::chapter/section)"/>
        <xsl:variable name="subchapter"
            select="
                if (@epub:type = 'subchapter') then
                    concat('#', pfn:generateChapterID(.))
                else
                    ''"/>
        <li>
            <a href="{$fileName}.xhtml{$subchapter}">
                <xsl:variable name="heading" select="h1 | h2 | h3"/>
                <xsl:value-of select="$heading | .[not($heading != '')]/@epub:type"/>
            </a>
            <xsl:if test="section[@epub:type = 'subchapter']">
                <ol>
                    <xsl:apply-templates select="section" mode="toc"/>
                </ol>
            </xsl:if>
        </li>
    </xsl:template>

    <xsl:template match="node() | @*">
        <xsl:copy>
            <xsl:apply-templates select="node() | @*"/>
        </xsl:copy>
    </xsl:template>

    <!--<xsl:template match="img">
        <xsl:copy>
            <xsl:copy-of select="@*"/>
            <xsl:attribute name="src" select="concat('images/', @alt)"/>
            <xsl:attribute name="src">data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAGVAj8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK4jV5oYfF1yfEA1b+zmgQWLW4lNsvBMhcxdHzjl+2Nveu3rEvX8TwXczWEGlXts7Dyo555Ld4xtGcsEcNzk9BwfbkAz4ZdIXQ7d9OvbjUbOXU4gjG+djE5kUbd2d2FI5QnuQeOKu3GratNfajZ6Xp1tI9mVHmXNyUVyyBgOFJB5xnp/Kqdr4Yu4obiaae3a9vNVi1G4EYKxoE2LtTqSdsY5PU5PHQbVjYS22qapdOyFLuWN0Ck5AWNVOfxBoAw08UapJpdjrP9jRR6dO8Syo90PPjVyF3AAbThmHG7OAT14q/JrGp3Gs3+m6fp8DGzERM9xPtRt4JwAATkY+nv2qNdCuh4PtdI8yH7RF5O5snZ8kiscHGegPaqkb6qnirXv7Mgs5mP2YMLmZo9vydRtVs8Z44z60ALDq8et3nh67SMxMLy6hljJzskjSRHXPfDKee4pl34zZYLu7sV02e3tXdDDJfBJ5tjEPtXBAPDABiMkc7c5q3pvhuXTk0gCaKSS3uJ7q7cAqJJJg5cqvOBvc8E8Cq8Gka1pcstta2uk39nJPLLHNdO0UsIY7ghCowkwxIBypxjqRkgHTwTJc28U8RzHKgdT6gjIrkvDmbfxB4vdprqZLO7RIY5bmR1RDbQuQAxIHzEn8TXXxqViRWCghQCFGB+HtXOaVoup2upeILi5FoI9VlEy+XKzGMiJIgDlRkYTOffGO9AESeJ9TTT9L1W60qC30+9kt42BuS00RmIVDgKVI3Mgxnoc54xRpN5rUvjLX7eSK2ayilgCbrtyUUx5+VNmAT1Iz171avNAuLrwtpmlebEs1rLZSO/JU+RLG7Ad+dhA+tOTT9TsvFFzeWsdpNZX5jNw0szJJCUXb8qhSHz7lce9AGZN46ji0+fViLFdOg3s8b3Y+0NGpILhACOg3Bc5I9DxWjJrmpTazfabpulRzG0ELGee58uMhwSRwrNuAHTGDxyKp2mj61pUMdhbWejXdsjOEuZ3aOREySgKBG3kA4J3LnGeK2rLTpbbW9UvWdDHd+VsUZyNi4OaAMttf1i4j1STT9Jt2XT5pIv9Iutnn7Bn5dqnGenP69alu/FEaiwS1+zLLeW4uQ13P5SRxnGMnByTnAA9DVqw0qa0tdUid42a7uZZkwTgBwMA+9Zr+Hr+1TS7u0FncXdnYCzlt7kkRTYCkEPtJUhlPODkMcjpQBl674ovbnRI206S3S8t9Zs7S4MF1uQh5Y+AwHKsrgHIyATwa7e2a4a3U3UcUc3O5YnLqOeMEgH9K57UdE1HWNAWCaLT7K9jvLe7jSBmePMUiSbWbapOdpGQOMg4rfsmu3s42voYYbkj95HBKZEU+zFVJ/IUAc54mF9rGo/wBi6ZdvbT29o168kcrIVkztgVtuCULByRkZCY5zVlvFBbw7pl/a2fn32olIoLRpQn70gllZucBArliAxwpwDSweFrWbUtS1DVYYLm5uph5Zx/q4VUKiZwP9pu/LmqI8JXVqm2weziWy1L7fpqMjbUDoVljcD13y4IzjcDg45ANOfV9S060Z7+wt2nd0itltrgkTSMSAvzKNuOueeKbdazqekWd5earYW32eGEPG1rc5LuTgRkOqgZJGGzjrnGKZNY63q1gpvk0+yu4JkntlgledA6k/eYqhII4wBxnvReWGta3pl3ZXy2FkHT9y0LvPiRWDIxBVPl4BK/hnvQBHbeKf+JrZWV22nt9uZo4fsd15zK6oz7WGB/CrfN0yMdxT9G13UNbitL62tLI2E5yw+1N50SkcFl2Y3ZwCpIxnrxiprCHWVvx9q03R4IEH+ut5XZ3O09FKLt5x/E3FUP8AhG57rWbPUZtO0qyvIJQ8t9Zk+bMozlPuA7SeuWNAFrStfvNZP2ixt7J7MTtC6m5ImTa5Riy7cAjBO3PbrW3eMVsbhlJDCNiCO3FcrdeHdQ1TUbea60/SbSaC4SX+07OVvtDKro2wKYxgPtKsC5GPXPHV3MZmtZYlIDOhUZ6cigDmtK0Bbjw7pt1b6jqUF8bONhMb6WQFiqnLI7FW5HcevrT9I1j+1v8AhHrm6t9t1cW0zsY5jsR12q+B0YEk4z0pItO8ULo0GlxXWnWSxwpAbuLfLIqgAEqrAKGwOCcgHsavW+grYXWjrZkLaafbSwYdizncEwc9z8pJJ7mgDO1LxXcaPck339jrbicRtGmoH7QEZtqsEKDLHK5XPc4Jxzfl1bUbnV7mz0m0tJo7MqlzLcXDJiQqGCKFVv4WBJOMZHBzWDF4X12Pw/LoMaaTHAHUi+LO0tz8+9mdAihXPOSGYZOcVZvLmLw/r2rTQ63o1ql2I7q5hvpCskLBAnmAbhlSsa8ccqefQAnHi65Ol6DcjSxJcarctbGCOfiJhHK+QxUbh+6x0HBz2wb13qWq2ljHNcQ6TaSFnDme+YRqM/LhtgySOowMe9ZOhaPcXug+E7liYvsNw946SoVZleKZAMdj+9BwfQ1f1jSdSfxLY6xYW+n3flQNbNDeu0ZiDMrGSNgrc8YIwM4HIxyANXxW8mjfa4bNLmdb5LJo4LhSjMzKNyucAjDA9u4pH1nxAmrf2Z/Y9k08sPnxSi9IjRQ4Vg+U3ZAZSNoIPIO3rSxaDf8A2eUTyWvmyarHeny9wUIuzI6dflNar2MreIYtQDJ5KWjwFcnduLqwPpjCmgBmh6lcajb3IvLZLe5tbl7eRY5N6HGCGUkA4KlTgjjOPetOs/TLGWym1F5GQi5uzOm0nhSiLg++VNaFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFNCKrMwUBm+8QOTTqKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKY8MUjKzxIzL0LKCRT6KACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKx7x5b3UZLMTSQ28MatIYnKvIzZ43DlQAM8YJJHPByAa7MqKWdgqjqScAVm/8JFo7PIkWpW88kbbXSB/NZTwcELkg8j86ppoOmL5JltVuXh5jku2a4dTjGQ0hJzjIznPJrRACgAAADsKdh2K66/FMge3sdQlB9bZoj+Um00+PXrAyCOZ3tZCQALmMxgk9AGPysfoTU1NZVdSrgMpGCDyDRYLF+isNdLjt/8AjwnmssY+SFgY8Dt5bZUfgAffpUi3+p2vFzaR3af89LUhG690c4wPZifaiwWNiiqVrq9jeS+TFOFnwT5EoMcmB32Ng498Yq7SEFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABQSAMk4FYKtLq0k8jXdxFbJNJAsML7M7GKklh82SQ3QgYxxmm/8I/pbxRx3Fot2qYKm8drggjBBzIWOcgHPXinYdjWTU7CS5Nsl9bNcD/lkJVLflnNWqynsbSS3NvJawNARgxtGCv5dKgFhNbc6feywdf3Un76LP8AuscgeystFgsblFYr61PYLnUrVPLH/La2kDADHUocMPou6r+n6pZarC0tlcpMqnawHBU+hB5B+tIRbooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArHj/wCQ3qH0i/8AQTWxWPH/AMhvUPpF/wCgmhDRbooopgFRyS7GCKjSSHkImM49eSBipKZac3l0T1ARfwwT/U0DGhb1zxDFGPV5CSPwA/rSizumBEl4F9PJiAI/76LVI2o2asV+0xsw6qh3EfgOaYdRDDMVtcyf8A2f+hEUARXOh2N9D5V8sl0ndZJDj8gQP0qPRi1tqF/piySPb2wiaHzHLsoYHK7jkkZXIySecdAKlfUJ1YDyrdAenmXGCT6YA/rVbR5hca/q0qgjMcAIPYjeCPzFAjdooopCCiiigAooooAKKKKACkZlRSzEBRySTwKWuY1C1iv/ABd9nuR5kIt4GVGOQpzOSQD0J2ryOeBzxQBoT+JtMjwIZWumOdv2ddykjjG84QHPYsD+VQf2rrF2SLPTEhQj5ZJ2JYH3T5QR06Oa5Lxh8Q7bwTq39n2+kCe4MSyeYZMZBJGC3J7VxF78a/EE7EWttZ26HsQXI/HI/lTGewtZeIrqNRLrCWrAgk2kKYb1GHDYB6cNnnrUd1ovnwNHqGvXgGOWguntj+aOMV8/X3xC8VagrLNrE6of4Y8Jj6Ec/rWFdX95fHN3dzznrmWUt/M0AfQNxc+DtKLrL4mlBDFmiF4CSSckkDrkn9a14LeKx1zThZzT/Z7u1md45JCVYqY9px0B+Y8j1r5er6jX/kKeH/8Arxn/APaNAzXuZGigLJjcSFXPTJOBn86cdPtwN80kr46l5mA/EAgfpUV5/qB/10j/APQxXH3n9v388Ulnf6Nao8SuZJ7Y3M5YgE4XeMD2pgdjHNpNuxMH2beOvkqGb8dvNVba4juPFzNETg2ADAqVORJxkHnufz965L/hHNWuYy2o+LNcmXB3JapHZx/QcBgP+BZ9zW54ejWHxLJEjMyJZBVZpN5IyvJOTk0gZ19FFY1j4ihvtan09YSgQyCKVnGJjGQsm0dflY4/CpbSHGEpJtLY2aKKKZAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFY8f/Ib1D6Rf+gmtiseP/kN6h9Iv/QTQhot0UUUwCs6eQrO8X8Msqqw9QI2bH47cfTNaNZd0C14gEjRn7QvzLjI/dSevFAzjLq9+J97cyR6Xp2iafapIyI91K0hdQcK2EztyBnHXmq8vg7xvfFm1jx/Jb27/AHorO3WPAx/C5II/Imn6j8WfCVpey2SzatqV9E7RtBbxOGLKSCAPlBxg1VXx94gvGDaB8N73nrLfkW+fTBYc/n2oAvaL8OtF0zU7fU5da1nVruBt0TzztMqHBGQFHoe5Ndh4bO7WNXOCM7Dg9fvy1ymj3HxNv9Wt5tUg0ax0zdmWCJmebGOm4ZXOcdwOtdZ4c51rWPqn/octAdDpKKKw/GLbfCWoklwNgyUzuxuHTHOfpUt2Vx04c81HuzcorndNs9H+3xtb6XewyrkrJLFKqjj1biuioTuFSKi7IKKKKZAUUUUAFc/J/wAjsf8Ar1g/ncV0Fc/J/wAjsf8Ar2g/ncU0NHi/xn/5HpP+vOP/ANCavO69E+M//I9J/wBecf8A6E1ed0AFFFFIQV9Rr/yFPD//AF4z/wDtGvlyvqNf+Qp4f/68Z/8A2jTQ0al5/qB/10j/APQxXC6jDcG3tJZvFV9pVlJCkccEHkwbnCZOHlXLE4J4PbIrurz/AFA/66R/+hiqtnZWt3pWntcW0UxS3UKZEDYyoz1+g/IUxnm50rwjc3Yiu/7R1aQsMm8uLqZWJPHy4MbfQdOPau70O3Fp4rnt1VFSOzCqsYwqjK4A5rbhght02QRRxr/dRQo/Ssuw/wCR2u/+vQfzWkI2NYvjpukXV4qF3jjJRB1Zzwo/EkCuTng1XSNI0m5n0+Bf7KcSXFx9syShBEpwEAOck84HGe1dpPbw3KKk8SSqrq4DqCAynIP1BANPkjSWNo5FV0cFWVhkEHqDUSjc3pVlTVrX11/L/MUEMAQQQeQRS01EWONY0UKigBVHQAU6qOcKKKKACiiigAooooAKKKKACiiigAooooAKKzbvX9LsbtrW5u1SdVDlNrEgHODwO+D+VWrK/tNRg8+zuYp4slS0bAgEdQfQ0rrYt05pczWhYooopkBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFY8f/Ib1D6Rf+gmtiseP/kN6h9Iv/QTQhot0UUUwCsu6LfbU2rvP2hRt3Y/5ZSd61Kzpf8AkIxf9fC/+iZKBmRqOq2Xh5likSG3nlBcRW0LzMwz1IXaBk+v64rKHi+7u1dtN0bUriQZ/dsY4VOO+U3sM13EltBNIkksMbun3WZQSv0NSUwOc0T+0b+aU6rpEcFtsBj8yd5W3Z6EMP8AD9eLnhtQusauqgBRsAA6D55a2KyPDv8AyGtY+qf+hy0hHSVna7Yy6notzZwFBJIAFLnA4YH+laNFJq44ycZKS6BRRRQSFFFFABRRRQAVz8n/ACOx/wCvaD+dxXQVz8n/ACOx/wCvaD+dxTQ0eL/Gf/kek/684/8A0Jq87r6F8YfDQeK/EX9qT6l9ngWFYtipluCTnJPv6VVsPhH4UhfE0l7e8/xOVA/FcUBY8Eqa3tbi7fZbQSzP/djQsf0r6ZtPA3hqwVRb6BbSFULLJKNxyOgyasyavotkwtoZ7RbqNQXtrWPz5V/4BHluoPbsaAPniy8DeJ9QGbfRboj/AKaKI/8A0IivoRkaLWNBjcYZbK4BB7H9zUc/iC/tipj0q9ZWHyzXg8mH1y20O6f8CUDpU1lFdahfW+q3N7ZzRxxOkKWakrhypJLlju+4MYAoGaF5/qB/10j/APQxTNL/AOQRZf8AXBP/AEEU+8/1A/66R/8AoYqppt5Gul2aKsrsIEB2RsR90d+lMDTrHsP+R2u/+vQfzWr/ANouH+5ZsP8ArrIqg/kTWbpTs/jK6Z9m77LzsbcOq96QjqKKKKQgooooAKKKKACiiigAooooAKKKKACiiigAooooA56w/wCR91r/AK8bT/0KalkBt/HlqtsNqXFjM90FHBKvGEY+/Lipbzw88+rzalbavfWM00SRSLAIirBCxX76Ng/MelXNP0e206aedGlmuZ8ebPO5d2A6DPYDJ4GByazSex1yqQ+K9/dSt8ktfzW5fooorQ5AooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACseP8A5DeofSL/ANBNbFYhljg1XU5ZXVI0SNndjgKApJJ9qENF6ivM9d8b6ncy7dLP2S1z8shUGSQDqTnO0fhnjr2Gbp/i3XhcBv7TBx/yznQMr+x6EfgRV2Xs3UurLc53i6Sdrnr1Z0v/ACEYv+vhf/RMlRaDrsOt2rMFEVzFgTQ7s7CehB7qcHB9j6cSy/8AIRi/6+F/9EyVCaaujoTTV0aNFFFMArI8O/8AIa1j6p/6HLWvWR4d/wCQ1rH1T/0OWgDpKKKKQgooooAKKKKACiiigArJv9HmuNQS/s742twEWNsxiRWUbsccYPztznv0rWooA5DxA95pFrE9zr+qEzOI0Wyt7VTu69ZVKjp3NT6VaX887yy6jdTWxQACS4jL78nJPlKoHbufwre1C7trK0aW7DNESF2pE0rMT2CqCT+Ark9RGl2ksRg0vUrVJAVDwhI4gB/Dscnb/wABXPH0pjRvS21hCB9qki68G4l3n/x4msf7Vpvhu1ggtddFvGu2NIrqNWjbkADICncegw3J7GshbiCJ5immxBCQsby3cs6Px/zzO1VOc9OOOvYJbXl1Z28dtbyWmneUoDDT7SOGNiMfKoYPj0xnI/WgZ2eiatNqsUxmsntzE4UNnKSAjOVOB+PHHqaj1S30O133l7cQae/3nuROICcDqxyNwH+1kVx8k9zcOrTXE7O33w077CB1AUsUPucVBDGtojS2sUVuHcjECiMMxPJyOOvO7qeeaLCsdFc3zxQ7YNUtb6PKFDcfuS7A5x5oHlsTwAMLWBPoXxAv7gJaaqdN05I1jSD9yjgAAZ3hZS2euML179acs32efcjHbtIJDFNxPXPPT9cnvU9lc3VjIkdu8lvnosZCAgc/6s5Qd84AY/rQMoD4RXd/HImueKL++jlJLxyzzMeeoBEipj22V3Ph3wxYeGrTyLPcxKhS7hR8ozhQFAUAZPQfXNU4fEd7bQh9RsGMeQpliUp1OM7WOMcjo5PX5R36akIKKKKBBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABVW7v47RhGI5Z52GUghXLN784Cj3Yge9OvrtbKzkuCu8rgKgOC7E4VR7kkD8abY2rW0JMriS5k+aaQDG5vb0A6AelAGfcXniXzM2ei6Y0RHW51N4nB91WBx/49VgancWyg6jYvAveWBvOjU+5ADAe5UAdyK0qKAER1kRXRgyMMqwOQR60tZz/wDEsuY2Xiznfa69onPRh6Angj1IPc1bubqC0i824lWNMgAsepPQD1J9BQBNRWaupXcpJh0m52fwvKyRhh64J3D8QDT4tUBlWK7tZ7J2bannbSrn2ZSRn0BwT6UAX6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACuA8e3L2VvexHcv2wwbWBxuA3bgPptXPsw9a7+srxFoya9odxYNtDsA0TN/C4OQfb0+hNONr67Ckrpo8RvrnztmxcKoxuHeqkRIkBD7SOc1pXcc9kJ7C+jZJ4jtUOMHqP0xzWYqM3TsM124NQhQnTkuVLS/dPqeJblupaHZeEHe08TaeqNu+0xyxyEdCNu8H8CuM+59a7+X/kIxf8AXwv/AKJkrjfh1pYd5NVeZH2KYokDAkEn5mI7cAAfU+1ddeFftal5TEonBZ8gbQIZM8mvOpwcFyt31Z62Fg40kmatQy3dvCcS3ESH0ZwD/OuV1Dxt4H01ZDe+IrKUoSHQXJuCCOo2KW59sVgt8afCaTLbaJYanqchBISwssYAx2Yg9+wNaG56L9ujY4jjmkP+zGQPzOB+tUPDRLaxq5KlSdh2nGR88vpXA/8AC0fEd3cBYvCS6Talwpu9ZuxCEHdjGQpYD0UnNeheGIZWkvtQdGSO6ZfK3DBZRk7semXIHrtz0IoDodDRRRSEFFFFABRRRQAUUUUAFFFFAEF3aQX1uYLhCyEg/KxUgjoQQQQfcGqJsNQtc/Y77zo858i8XdxjoHHI+pDGtNyyxsUXcwBIXOMn0rMGuwNpkF2kbtJNIIVt+j+bnBQ+hXBz7AmgDJubWyG0X+nXGnsp4mt/ni6c8r91fdgtYhjsZbiSC31G1nZcENHKrSFDnBCoWODg8kc+ld+99aR3S2r3UC3DjKwmQByPYdaeskIMiq8YMf8ArACPl4zz6cc07jucLFp00sfnW9rfySHCkR23lHGeg80x8e/txV6Lw9eGdGSyijh2kN513yDx/AqEHvn5x/h1LXtoi7nuoVXYJMmQAbP73096g1jVIdG0K+1aZGkhs7d7h1jxllVSxAzxnii4XMqDwzOqSRzXdusbNlRBa8qMd/MZwTnPO0duKuR+HrYIiy3V7Ls5yLgwg/URbQfpjFJBr+L5bS/sJ7BpI2kikleNo5AoywBViQQOTkDjoTzUY8QXMtst5baHf3Fm2GSRGjDOh/iCFgcY5x1I6DPFIRdg0PSre5NzFp1qtwQAZvKBkIGcfN14ye/c1foooAKKKKACiiigAooooAKKKKACiiigAooqre3ZtUiVEEk87+XChOAzYJ5PYAAk+w4ycCgC1VO6v/ImEENvLdXGNxji2javqxYgAZBxzk4OBwcQf2dfsfMfWrkScHakUQj+gUqWx9WJ96Zo1nf211qst+8cjXFyrxNHnaEEMaYAPKjcrNjJwWPJ60ARy3M1/qWn20lnc2xjlaeRZVDKyqpA+ZSR95lOM5+XpW1RRQAUUUUAQ3dsl5Zz2smdk0bI2DyARjiqun2c4Ed1qJjkvtm3KcrGO4TPrjJPf6AAaFFABTJYo54nimjWSNwVZHGQw9CKfRQBQtZHtbr+z5mZwUL28jHJZAQCpPcrkcnqCOpBq/WXrbCBLG8+YtBeQqAO/mN5Rz7Ykz+ArUoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiudvr6fTNS1XDO/m2S3FsjNkeYuUKj0yTF+dULc3MNlpegtdXU08WpeTLOZj5hiiBmUs2ckFRGp6534OQTQB2NFcq/jGErPcwyWT20MzwmLz8zPsfYxAA4IIbC9TjqKitr3WLWbxBPa2trNb2987kSTsHcCJCVUBcA+nJzmgDr6K56bxGXvVgtms4Q8Ec0LXspj87fnAXjtjnqcnpVPVtSvFi8QraDyri2SA7zM5A3Lk7R0BHsBnvQBu6poWma1Hs1C0SbAwGyVYD0DAgj86z7TwT4es7gTx6erSDp5rs6j/gJJH6UXuvzafPa2F2+nw31wkkuXmIjVFKjPIBY5Yccd+fW/o+pjVbWSTCbopWiYxtuRiMHKnuCCPocjtR0sJpPUmu9Msr4hri3VpFBVZVJWRQf7rjDD8DWPfeHb6USJbanG0Eq7XivrfzscEcFWXjBIO7cTnrWVBqOs2mo+MriygtriK0vg+25uGTIFpA2xcKcdzn1PSt0axeX92kOlwW5QWyXEslw7DG/7igAc5AbJzxxwc8BRyWn/B3RbRUL/ZFkVt+620+Ic5ycGbzSB6YPA6Y4rqIfBukxoFl+2XAH8Mt3JsP/AAAEJ/47UbeKCy2Q8uCzM6SF3vJdqLIjbDGDjk5z6cDpzwputZfxHaxoLPynsi7p5zlc71BIO3nrx9aANSx0PSdMJNhplnaknJMMCoSfUkDmr9YtzcGTWJ5lR5Y9Lty3lx9XmYZ2j3CD/wAiVV0/xQs+kz6pc3GmG1t7ZprkWt0ZGgZRllOQOmGGTtOR09AR0lFcza+KHk1Gyt5PsUiXgcAWszSPC4QuA3GCpCsN3GDtGDu4hsfFOo3PhW08SXNha22ny2sV1KPtBZ40baXb7oGFUs3XoO2eADrKKxr/AF9LCW/JjDQWVuskrhsEyMflQfgMn/eWqI8UtGzpIbKdjbSzJ9llLhGRd21uOh5w3HTpQB09FZukXl/f20d1c20EEM0SSRhJSz8jPI2gD8Ca0qACiiigAooooAKwbbTI4/Gd5dhZNhtY3VT/AKtZWZ1dh/tFUQH2Huc71FAHn9/BDD4f13TZ4Gm1u7up5YCLc75JGf8A0dwwVhhB5Q387fLycYrUe/i07V9ft7pZxNcrHJAEgdvNHlBDtwDkhlOR24JwCK6yigDi9J0yK61XSfttksqR6FEAJotwV8jjnvjPvWp43gkm+H/iG3t4mkkfTbhI441yWJjYAAD+Va/mP/anl7js8ndj33VZoA5bUPCc2pWV41zqt3PdSWE1pbZ2xrAZFwWUKB8x4GTnAHGMnNqy8S2i2MMdxb3VvfrGoex8hjIrY6ALkEf7QO33rfooAKKKKACiiigAooooAKKKKACiiigAooooAKzNUZobzS7j5fKW58uRmONodGVfxLlF/wCBVp1m62pks4IgxUPdwAkdwJFJH4gEfjQBpUUUUAY0V3qJ8Wz2Lz2xsltUnVBARICzMuC2/B+6D931plv4r065e02JeLFduI4p3tXWMuc4XcRgZwQD0zxnJFPjhu/+Etmu2tHW1a0SASl0xlWZs4znHzAdKpwaPep4Y0axaNfPtZ7d5RuGAEcFue/AoAtaf4hS5n1BLiCaCO1ldTM8TKgRVBJLHgHk/hVmHW7WVwrJcRbkaSMzRFPMUDJK59j0OD7Vk3ek6he2niHSGg8qLUDI0F4soKjdGoG5QQ4IYHp27g9HQadNJIDLo80c0cbgTS35lQMVK/ICxJznGSF4NAFgeMNIOnR6gHuDZSCHZcC2co5ldUQKcfNyw6ZqzaeIbG6muomW4tpLaITyC6gaL92c/ONw5HynPp3xkVnX+iXlz4P0nTY1T7TbTWDyAtwBDNE78/RDijXvD91rF7qCxuIornSXtFmJPyyFsjgEHH0I+tAGkmu2zgjybpGMbSRCSBlMwAydo9eehwfajQNY/tvSbe7NvPC0kMcjCWFowSy5+XdyRVGwsJGvIXn0iaGSIN+/lvjKikqRlAWJOcnqBwavaAl3b6Tb2V3aGB7WJId29WWTauNy4OccdwDQA7XLW7vNNEdkkLzrPDKFmkMasElVyNwViOFPb8utPj1F1mWG9tJLZmIVZNweJmPYMOh/3gM5AGav1Fc28d3azW0oJjlQowBxwRigCWiqWj3Et1o1lPcFTO8KGQr0LY5I9s5q7QAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBlatokeq3mm3LTyRGyn83aoBEq8HY3tuVG4/uimpoEaeKn1z7RIWa38kW/GwMSu6T3YhEXnoF46mteigDGh0a7sWkisNTMNpJK8xjkh8xkLsWYIxPAyTwQcdBxioJPDt2W1KOPVSlpqMxkmj+zgugKKpVGzxkL1IPXjFdBRQBi6loUt/aS6eLqFdNmi8lraS1V9qbdpCnIxx6hqZJ4ZieDVYVupY1v4I4QwALRbE2hgTnJ78it2igDGl0e8lltr06iq6lbo8YmSHEboxUlWj3c8qpznI5xjJFaNnFcQwkXVyLiUsSWEYQD2A54+pJqxRQBkR6DHGNc2zvnVpTI+QP3Z8lIuPXiMH8aqxaSba/VdN1MQ3kVnDBcLJF5iui7tjbcjDctyD0IyDgVvu6xozuwVVBJJ7CvLtL8SN/wm7ahKdsFy5ibOBtQ4C5+mB+VAHcxaJdWdhBZ2eojykTbJ9qt1l81iSWc4K4Ykknt6AVFbeGzpg07+zLwwJZW5tvKeIOsiEqeORtI28YOAD06Y36KAMzTLKeLSpPNJt726LzSsuGMcjfodowo7fKKqP4ZS/uJJtYkgu2e1ltD5duIt0cm3eG5JOdo9B7VvUUAZVlp2pWwiin1c3NvEmz5rdVkk4wC7A4J7/Kq1JpOjwaV4cstF3GeC1tUtcuOXVVC8j3ArRooAxLHw1BbaBPpVxczXYnLeZPJgOegXp/dUKB/ujOalOmahNbz213qomhkhaIbbYI3zDG5jnk/QKK1qKAILK2FnYW9qG3CGJYwxGM4GM/pU9FFABRRRQAUUUUAFFFFABRRRQBT/wCYx/27/wDs1XKp/wDMY/7d/wD2arlACM6opZ2CqOSScAVWsdQtdRjkktJVljjkMZdTkFh1we9WJI0ljaORFdGGCrDIP4VkeHUSNNSRFVUW/lAVRgAcVaScW+pLbujZoooqCgooooAKKKKACiiigAooooAKKKKACqWq20l1p7LBzPGyTRDONzIwYKT2Bxg+xNXaKAIra4ju7dJ4iSjjPIwQe4I7EHgjsRUtUZraeGZrmx2bmOZYHOFk9wf4W9+/Q9iK8uvw2oT7XYanC7sFCpZST4PuYg4A984oA1qKzftN9e/JbW72kR63E4G7H+wnr15bGD2PSsPxLdL4atoWs7iWM3Mo82PcGLgfebJyQxGBn3z1oA66isi3vJbK0iEkc95aeWDFdQgyMUxxvX7xbHcA55PHSnHxDYgRkR6gxkOAq6dOSOM8jZ8v1OKANWisxoLjVCHnE1nChzEiSYkLdmbHAx2Xkc8+gX7bd2Z2XlnJKg6XFqu8H6p94H6Bh79qANKishPEunvbGcR6iFAJ2tptwr8f7Bj3Z9sc9qlF9d3h22dlJEhGftF0uwAeyfeJ9iFHv2oAbf8AiCx06ZopkvpXXAb7JYT3O0kZwfLRsHGDz6j1oXUJdTgC2MF1Csi8z3EDQmMHuFcBt3oCPr6G9bWyWsIiTJ5JZmOSxPUn3NTUAVl+yaVp8cZeO3tYEWNS7BVVRgAZP4Cof7d0j/oK2P8A4EJ/jV+igCh/bukf9BWx/wDAhP8AGj+3dI/6Ctj/AOBCf41fooAoprWlSOqJqdmzscKqzqST6Dmr1U9U/wCQdL+H8xVygAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAAgEEEZB7VlQ20H/CQXg8mPAtYCBsHB3y/wCFatZ8P/Iw3n/XpB/6HNQBoUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBT/5jH/bv/7NVyqf/MY/7d//AGarlADJozLC0YkeMsMb0OCPpVGw0hNPmkkju7pxIxd1kcEFj1PTrWjRTUmlYVluFFFFIYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFcX4v8OX2q30d0tzCsCmOGNDuyCzAZPbqfyFdpVLVP+PWL/r5g/8ARq0ARaDY3Om6RDZ3UqSvFkBlz93PA5rSoooAKKKKACiiigAooooAKKKKACiiigCnqn/IOl/D+Yq5VPVP+QdL+H8xVygAooooAKKKKACiiigAoprusaM7sFRRlmY4AHqa4+b4l6JFO8aw3sqq2BJHGu1vcZYHH4VUYSl8KLhTlP4Vc7KiuK/4Wfo3/PpqH/ftP/i6P+Fn6N/z6ah/37T/AOLq/Y1Oxf1er/KdrRXFf8LP0b/n01D/AL9p/wDF0f8ACztG/wCfTUP+/af/ABdHsanYPq9X+U7Wisbw54lsvE9pPc2Mc6Rwy+UfOUDJwDkYJ45rZrNpp2ZlKLi7MKKKKQgrPh/5GG8/69IP/Q5q0Kz4f+RhvP8Ar0g/9DmoA0KKKKACiiigAooooAKKKKACiiigAooooAKKKKACiobm6gs4TLcSrGmcZPc+gHc+wrN/4SFJYt9npupXPzbcfZ/IPXBP74pwOvuOmeKANigjIwaxzf6vJJiPT7WKIj70tyS4P+6qY/8AHqYqazIX8/U7dFJ+X7NabSo44Jd2BOc84H0oCxwD+G2HjT+yQpEJl3A/9MuvX6cfWvWQAoAAwBwBWALfULfUBff6LeyCIQguDDIFzk/MMqT6Dav15q4mvWikJeCSwckDF0Aqkk4ADglCT6Bs0xmpRQCCMg5BopCCiiigAooooAKKKKACiiigAooooAKKKKACiiigArC1iK0tDLeX2rX8CycRpHMVCYHRVUc+vOfyrdrLudSu4pZYRo11OM4jeNoyjg+uWBHvkfnWlO99CZ2sTaM142jWjX5zdGIGQ8ZJ98cZx1xxml1T/j1i/wCvmD/0atRaBYzaboVpaT7PNjU7ghyq5JO0ewzj8Kfq522cZ/6ercfnMgpTtzuwQ+FXL9FFFQUFFFFABRRRQAUUUUAFFFFABRWVrWuRaPEp8l55TgmNCBtUsF3E9hkj69q1apxaSb6ium7FPVP+QdL+H8xVyqeqf8g6X8P5irlSMKKKKACiiigApskiRRtJI6oiAszMcAAdSTTqy/EoDeGNUBGQbWQEH/dNNK7sOKu7Hm/jLxuusO1hp8wWwU/M4ODMf/ifbvXG+bH/AH1/Ouj+x2v/AD7Q/wDfAo+x2v8Az7Q/98CvUhywVkj2qfLTjyxRznmx/wB9fzo82P8Avr+ddH9jtf8An2h/74FH2O1/59of++BV85ftF2Oc82P++v51javq4UG3t2yTwzD/AD/n+fcy2dr5L/6ND90/8sx/hXk8v+tf/eNa0rSZvQtN+h738E+fCN0T1N23P4CvS680+Cf/ACKNz/19N/IV6XXk4n+LL1PCxf8AHl6hRRRWBzhWfD/yMN5/16Qf+hzVoVnw/wDIw3n/AF6Qf+hzUAaFYviqaeDQZHt5ZYn86FS8OdwUyKGxj/ZJraqtfXM9rb+bBZyXbBgGjiZQ2PUbiAfpmrpu00yZq8WjL0Z7CW8f7LrF5cyxr88FxKcgHuVIB/Gt2sKGG41HxDb6k9lJaQ2sMkSmUjfKX29lJwox371u06trihewUUUVmWFFFFABRRRQAUUUUAFFFFAGLM3m+J3R+Rb2kbx+xd3DH8o1/X1q7VFv+RrvP+vG3/8AQ5qvUxhRRRQAUhAIIIBB4waiYvNcfZ432YTc7jBKgnAwDxk8/lUg06Jv9bLPIfeUr+i4FAzPfT7a0G+0uX07/ri4EfXJ+Rspz3OM+9IuuXluBuhTU4/79ip39ePlJK/U7h9K1Y7K1iffHbxK/wDe2jP51YoEV9P1K31KJnh8xWQ4kimjaORD7qwBH16HtmrdYsH/ACOV5jvp8Gf+/kv+NbVIQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFUNY/48o/+vq2/9HJV+qGsf8eUf/X1bf8Ao5KAL9FFFABRRRQAUUUUAFFFFABQc4460UUAcTqkOqWvhm6a8s4nuZnje4uBcZyd68KNvCjoB+fOTXZwtI8StLGI5CPmQNuwfrSTQRXERimjWSM4yrjIODkVJWs6nOrWIjDle5T1T/kHS/h/MVcqnqn/ACDpfw/mKuVkWFFFFABRRRQAVy+r+ILLUPCd3PapdywXFozxSi1k2OrLkNnbjBBzmuorgdN1Oxg+EthYzXUUd3HosUTwO2HVxCAVI6gg8Yqo/EiofEjmaKKK9I9YKKKKAGS/6l/9015BJzK59zXr8v8AqX/3TXkEnMrn3NdOH6nZhOp7n8Fr23i8Nz20kmyV7o7N6kBzgcBsYJ46A5r1OvKfg3PYS+F7nTrma3aWa4Yi3kYbnUAZIXqccV6F4evTfaT5hk8zyri4tt+SSwimeIEk9T8nPvmvJxP8WXqeJi/48vU1KKKKwOYKz4f+RhvP+vSD/wBDmrQrPh/5GG8/69IP/Q5qANCiiigAooooAKKKKACiiigAooooAKKKKACiiigDEb/ka7z/AK8bf/0Oar1UW/5Gu8/68bf/ANDmq9TGFFFFAFaKVIdSvJHOFWCH/wBCk4om1GWMFn+zW6dmmm5/EdP1qrcsq30xdgFC25JJ4+/JXEXvwx8LaxqM1/qlxfalJLIXCCd3jjzjKqExgcetAze1H4geHdOLpe+LLCOSP7yW5Ut+XzGufi+LvhbUdTtrHTm1fUrieVYgY1dFTcQNzZIwozycVs2Hw/8ACmnhPsnhS2YpjbJNEjHI75cls+9bm6KxQR7tOsgeFQvkH0+X5aADSZGfxXeqzFtlnEoJOTjzJcZ/l+FdGWC9SB9a5nRdw8WaiHYM32WPJAwP9ZL7mq3ie2tLnxfoqXumDUYhaXR8gxLJzuh5w3HFTN2VzSjTVSfK3bf8Fc7AEEZByKK5Lw4ltaeJL6CG0fSkmgQwac0exWCM26VduUydyggHPQnrXW0Rd0KtT9nKyCiiimZBRRRQAUUUUAFFFFABRRRQAUUUUAFUNY/48o/+vq2/9HJV+qGsf8eUf/X1bf8Ao5KAL9FFFABRRRQAUUUUAFFFFABRRRQAUUUUAU9U/wCQdL+H8xVyqeqf8g6X8P5irlABRRRQAUUUUAFZfiT/AJFnU/8Ar2k/9BNalZOvubjTbrTbdDLd3ELIsa/whsjcx6KvX64OATxTjuio6SR5pZ2T6lrNhZJOYfOd8sACDiJ2APtkD0p11az2V09tcxmOaP7y9vYg9wfX/I7HQvBs1hqFvqN9eI80GWSGBPlUlSpyx5bgnstbGu6FBrVsFY+XcR5MUwHT2PqD6V0+3Sn5HW8SlPTY8xqW0tLm/u0tLSPzJn6AnAUDqzHsB/8AWHOBT0sLqTVRpaon2wyGPaW+UEDJOfTHPr7Z4r0nRNDttEtDHF+8mkwZp2GGc/0A7Dt9SSbqVVFabmlWuorTc8uv7NtOu7+yedpzC5XzGUDPyg9B2549u56147L/AK1/9419TX3g3SdQvJ7qb7SJJzucJMwBOAOn4Cqlh8NvCOnziePRopZdu3NwzSj/AL5Ylc++M1VHGKmtVdlUMfGlHVXZyPwmie48G3NkLUuZbknzJYv3aDA+bJGGI7AZ5xnA5rvvCdnBYaD9ktlKwxXd0qgnJ/4+JOpPU+9X57pYCLS1VHuivyRDog7M2Oi/z6CoINDtoreONprtmVcM63Uke9urMVRgMk5JwOprjqT55OXc4KtT2k3N9TTorP8A7Gtf+et9/wCB8/8A8XR/Y1r/AM9b7/wPn/8Ai6gzNCs+H/kYbz/r0g/9Dmo/sa1/5633/gfP/wDF1Na6fb2ckkkXml5Aqs0szyEgZwMsT6n86ALVFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAGI3/ACNd5/142/8A6HNV6qLf8jXef9eNv/6HNV6mMKKKKAM2fnUJQcHi36/78lcTqY+Keo6jcx6dcaLp2nmQrDK6M0uz+9jDDPscV2tyu++mXJGVtxkHn78lUdes9V2wJo9vbz7y3nPeO0m3pjCswHc/l05oGcRJ4C8Q37BPEHxHv3B/5ZWm2DJ/Buf++ataX8J/C9lfRX7RapqN/DIsqXFzK+4spBU5+QHGB6jitqPw34muA6XXiIwwueFtEWPbx0G1Qcf8Cz71q6J4YGkXZu5NSvLucxmMmaVmBBIOSGY88evc0AS6IxbxXqJKMh+yx/K2Mj95L6Eirmq6Zfza3YanYSWwe2hmiZJw2G3lDkY9Nn61V0j/AJG/Uuf+XWP/ANGSV0tJq44TcJXX9XMe20q7l1iHVdSniM8ELwxRW6kIA5UsSTyT8g9AK2KKKSVgnNy36BRRRTICiiigAooooAKKKKACiiori5gtIWmuZo4YlxueRgqjPHU0AS0Vm/8ACRaJ/wBBnT//AAKT/Gj/AISLRP8AoM6f/wCBSf40+V9iuWXY0qoax/x5R/8AX1bf+jkpn/CRaJ/0GdP/APApP8ain1vQLmMJJq+nlQ6OMXSDlWDDv6gUcr7Byy7GvRWYfEehjrrOnf8AgUn+NadDTW4mmtwooopCCiiigAooooAKKKKACiiigCnqn/IOl/D+Yq5VPVSF0yZmIAABJPbkU7+0rD/n9tv+/q/40AWqKq/2lYf8/tt/39X/ABo/tKw/5/bb/v6v+NAFqiqv9pWH/P7bf9/V/wAaqanrtpY6bPcxT280ka5WMSjLe3FAGrXM6Xr1vF4Qs9cmjkebULVb9okG5zuQOR9FBC5PHAHUjJpnjnSb7ak7NaSntL93P+9/jiua8PjULT4UW5vtOcyS6RHGJI2BMcaxAIrKcEevG7lieKaV3YqKu0jX0jxlf6hr9pZT2dtFDcllwjszIQjN944B+7joOtWfE3if7IXsLBx9p6Syj/ll7D/a/lXCK9zBeWt1aTCGSF2JYrk4ZGU49D83X2/JQMfzrr9gua/Q7Vho89+gDIIYMwYHcGBIIOc5z1znnNd/4Z8TDUQLG9YLfKPlbGBMB39m9R+I7gcDScgqysVZSGVlOCpHQg9jV1KamjSrSU0dJrfirWbTWL+C2ngSGB9qKYdx+6Dyc+5ryzU/in4vvt8X9pLbIcqRaxKh+u7lgfoa665luLhrq4upFkmlJZmVduflA6evH+e3j8nMrn3Nb4ahBr3lqdODw1Nr346nv/wanluvDN7cXEjyzSXjM8jnLMcDqa9Hryr4N3v2bwpcJ9luZc3JO6KPcOgr02yvIr+1FxCHC73Qh12kMrFWBH1Brz8QrVZJHl4pJVpJdyxRRRWJzhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAYjf8jXef9eNv/wChzVeqi3/I13n/AF42/wD6HNV6mMKKKKAM6f8A5CMv0t//AEOStGs6f/kIy/S3/wDQ5K0aACiiigDH0j/kb9S5/wCXWP8A9GSV0tc1pH/I36lz/wAusf8A6MkrpaQmFFFFABRRRQAUUUUAFFFFABRRRQBBeXlvp9pJdXUqxQxjLM3b/E+1eN+KfFNx4iu8DdFZRn91Dn/x5vU/y/MnpfiJE95q1rbPcTrAkHmCNHwpYsRkjucD+fqa47+xLf8A57XH/fY/wruw0IxXO9z0sJThFc73MqitX+xLf/ntcf8AfY/wo/sS3/57XH/fY/wrr50dvtImVQSFUsxwB1JrV/sS3/57XH/fY/wrnPF1qLC3t1hmlKylgwZs9MVUWpOyKhJSlZGbc6qbq/gghOIRKuT/AHuf5V9WV8e2X/H9b/8AXVf519hVy5gknFI480iouCXmFFFFeceUFFFFABRRRQAUUUUAFFFFAARkYNM8qP8AuL+VPooAZ5Uf9xfyo8qP+4v5U+igBnlR/wBxfyqpqemx6lps9nkReau3eFzj8KvUUAYOm+D9H03DC38+Ufxz/N+nT9Kq60X0nwtfWLwSvarbOkE0SFwq4wqsByMDjOCMDJIrqKy/En/Is6n/ANe0n/oJqo/EiofEjy+iiivSPWCiiigBkv8AqX/3TXkEnMrn3Nevy/6l/wDdNeV2OmXmsasljYwtNcSuQqr/ADPoPeujDtK7Z14ZpKTZ7L8HNStrPwrcRzeduNyT8kDuOg7qpFeheHyW0tnKSIHu7l1EiFDtM7kHBAPIIP41neB/Co8I+H0sTMZp3bzJm7biOg9q6WvIryUqjkjwsRNTqylHZsKKKKyMQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAMRv8Aka7z/rxt/wD0Oar1V7+2uIb46hawG4ZoRFLCrBXYKSVK7iBn5m4JHXrxUcWp2skwgd2guG4EM6mNm9doP3h7jIpjLlFFFAGdP/yEZfpb/wDoclaNZly6x30zuwVQtvkk8ffkq19uiY4jWaQ/7MbYP4nj9aBlmiqvn3Tj93abf+u0oX/0HdS7Lxz800KD0VCT+ZP9KBFDSP8Akb9S5/5dY/8A0ZJXS1zGiKV8WairSNIRax/M2Mn95L6Vvyw3LyEx3Xlr2Xywf1pAWKKp/Z7z/n+/8gij7Pef8/3/AJBFAi5RVP7Pef8AP9/5BFH2e8/5/v8AyCKALlFU/s95/wA/3/kEUfZ7z/n+/wDIIoAuVHNPFboHmlSNSQoZ2AGT0HNV/s95/wA/3/kEVg+MLDULjQjHHJJcsZV/dxw8/XigDqqRmVBlmAHua4nwzoPiSyKNNf8A2W3HWBv3mR9Ogz7HNdVqFtBdvZx3MEcyecTtkQMM7H5waAOJ8bOr6/CVYH/RR0P+01c9W54ws7az16Jba3hgVrYEiJAoJ3N6Vh16FL4EepR/hoKKKK0NArkPHf8AqLL/AHn/AKV19ch47/1Nl/vP/StKPxo2ofxEchZf8f1v/wBdF/mK+wq+PbMBr2AEAgyKCD9RX1cYhpFxB9nJFnNIImhLZWIkHayegJABXpzkY5zjmO8fmYZrvH5mpRRWBeTXOp+Jf7JguprW2tbdbi5aHAaQuWCIG/hHyMTjk8c9a8xux5cIc7fZG/RWfaaW1nd+amoXkkRQq0M8nmKTxhgTyCMHvjmtCmhSST0dwooooJCiiigAooooAKKKKACiiigAoornLm/urf8Atu085/P82IWrt/AJgEXHsH3flQB0dUtYtZb7Rb21h2+bNA6JuOBkjAzWPaX99cjQLbzsTbpTfNj74hUxsPbMhU/QGlt/F0E8VtdmGNNOuplihmNyhdt7bY22D+FiVxzn5hkDnDWjuNOzucz/AMIhrv8Az72//f8A/wDrUf8ACIa7/wA+9v8A9/8A/wCtW7ba9eafZald3FrJNY2t7cGa5kuADHErnJUHqFHbI6cVqf25JPf3ltYWiXJs5FjmBuFR9xVX+VSP7rKckjOa29vM3+szOO/4RDXf+fe3/wC//wD9aj/hENd/597f/v8A/wD1q6O+1a+itrt9PRpZo9WhtmWaUABGMeQp2nAIbHrkk59Lc+vyxXkeni0h+3eR58yPdKqQqWKrlsZJbDYwuPlOSOMnt5h9Zmcg/g7XWjZRBbZII/1//wBat7wP4ItPCWn72VJNSnGbiYc4P91T/dH610GlalDq+npeQfdZnRl3A7XRirLkccMpH4Vzdl4xt7S71W2v01WaSG+lRDBplxOioMYAaOMrx9amVaclyiniJyjyvY7GiuX0bX7ibRdFjSGS81C9tTP+8JjUKu3LOdvy8soAxk88cHEzeK1C2sP2Jo72e8ez8iaZUVHRS5JfnIKgEYBJ3DgYOMjA6KiuevtU1iG90yOPTkBneRZIjcDDYUkYbb04znj0xXQKSUBYYYjkZzg0ALRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFRz28F1C0NxDHNEwwySKGU/UGmWl7bX0LS2s6TIrtGzIc4ZSVZT6EEEEU62uoLy3S4tpVlhf7rqcg844oAz30Xystp95Nanr5bHzYs/7rHIHspWomm1G0J+1WPnRj/ltaNv4x1KHDD6LuraooA5dr+3uLq4e3lR2RIS0ZO1l2uxO5TyuNy5yOM155qHxU8XA3CW3gyGwMbtGsmq6gkQJ7HDFAR9GIPY16/faTp2qbPt9jb3Jj+4ZYwxX6E9PwqlJF4d8K2huWg07S7ccGRYliUcZ5IHtTuO55GdW+KWttGsWp6fZxt946bp8twenTcUZOv8Atip4Ph94y1W4Mmsa54huRkfu5LuOzhYdcERvIcHp91T/ADr16513S7O1gubi+hjiuDtgJPMpxnCjqxwCcCm2mv6VffaPs99E7Wy750J2vGvPLKeQODzjsaAIdB0VtMR5rgxm6kRUIizsjRSSEXPJALNyeT7AADYrMtfEejXt3HaW+p2slzIpZIhINzgdSB3xkdK06QgooooAKKgu4Zbi2aKG5e2dsfvYwCyjvjIIz+FZMRurDxHbWQvp7uCeB5JEmCkxbSMMGAHBzjB/oauMOZbkuVjdoooqCgooooAKr3dnBexqk4chG3LskZCDgjqpB6E1YooA828XWcNnrsSw+ZhrZSd8rP8AxN3YmsRYblbVLqWHbbyyNHHIpyCVOCD6HjPuPocdL4wgub7xIkVjay3cqWqhkhA+U7mIDMSFUkdMkV0Gg6G0Hhn+zdUhjbzHdnjDbgAWJHPHI45HQ9K6lV5YKx2qtyQjY86orT1zQ59DugrEyWkh/czH/wBBb0b+fUdwGaPo1xrV2YocpChHnTY4Qeg9W9vz7Vv7SPLzHR7SPLzX0MyVLkWctzbwCSOB41mZm2hQzqvXBy3zZx/KuT8d/wCpsv8Aef8ApXu+peHYrjwzJo9iUt1JRlZgW5V1fJ7nOOvvXE6v8KL3WvIW41eCFI9xzHAWPOPU+1TRxMVK8icPi4KfNPQ8Psxm9gB6GRR+or6U1CzeTUNNFpeTPp9tfRvKsrmUNJkqFVmy2BuJPJAKqB/EKytB+Dvh7SmjmvXm1K4XB/efJHkHOQg/kSf512EyJPeWtjbIqwWriSXYMKmB8iD0PIOOwHPUZjF4iNZrl6GeOxMa8lydDTrBv7W9sdeGsWFqLpJYBBdwK4WQhSWRkyQpI3MMEjqOeK3qK4mrnHCbgyhZ313d3LK+mT21uoP7ydkBY8dFUnjk8nHSr9FFNCk03orBRRRQSFFFFABRRRQAUUVylj4gubP/AISm61i6jkstFmK5ig2tsFvHMzHk5PzkY9hQB1dFY8XiKCW8FqbO+jkkieaAyQbROFxkLzweRw2CfwNQ6T4kN3oFtqF9Z3FtJJHEdhjB8x3H3UAZs8+/6c0Ab1Y17osl14ksNTS4VIYEZZ4SpJlIyYznPG0sx6dx6UsviO1trO7uLuC5tmtQrSwyIN4VjhWGCQQTnoexpsvia1ieBWs9R3XEpihH2RsyEIXyB1AwDycc9cUAOsdE+ya7f6g0oeOcBYYsf6oHmT/vpsGq2m6HdaUltZW66abK3KrHIbciVYx0XAOMgcbvbpV+DWo7iznmS0u/Nt3EclqYx5qscEcZx0YHOcYqhqHidbfT9QaG1mF9ZojvbSqNwViQrnDYKna3IP8ACaAI5NA1GSz1DTTdW62N/NM8roGEqpIxJUYOM4JG7jHpUmq6DcancMCmnouR5d2sRFxCAQcKfXrzkfQ1dTVDLf2UTJNbeekrGGaIbjt285DcdffOe2KitvE1jdNaMkdwLW8fZa3ZjzFMcEjBBJAIHBYAHjBORQA2TQ5jb36xzxiWe+S9iLKSoKmMhWGe5j/WmXGj3b366oiae148CwTxyxko6qzFdrdRje3Y5z0FPk8UWcZlY294YIJmgmuBD+7jKttJJzyM9xn3qzfawuntK0tleGCFd0lwkYKKMZJ65IA64BoAt2UUsNokc/k+YM7vIQonXPAJP/16q6Tpzad9u3SB/tN3JcDAxtDY4/Sqtpqc8/jLUdO8xWtIdPtbiIADO6R5wxz3GI1qTVNQu01Ky0vT1jFzcrJK80qlkhiTALYH3mLOoAJHc9sEAp2+g32nW2lNY3Fsbqyga3kEyHZNG2DgEHKkMqnOD3GOciR9GvBaSK32C7kuJ2nuYrqEmNmIAULycbQoHIOfar1rFqlvMzXd5BdQbCcJblHDcYx8xBHXjHpUUevxNdpaTWV7bzyxPLCksY/ehcbgCCRu5HBIJ/A4AKUPh+8soLE2lzb+bbXMk3lOjeWEdWHlpg5UDIIPPQ8DPHRLu2jdjdjnHTNYWl+JBdaIl/e2s9vkKB+74kZjgBACSTnA/GrP9v28ayC4guLaWMx7opVG7a7hFfIJBXPXB4xzQBq0Vmya5ZRS6lGztu0+ISzjHYru49Tj+Ypuoa2unRyTTWF88EUfmyyxRBgi4yeAdxIHZQaANSiqVvqtrdX0lpEzGRYI7gMV+V43yAVPf7pz6ceoqWxvI9Qso7uEMIpMlNwwSM4B+h6j2NAFiiiigAooooAKKKKACiiigAooooAKKKKAON1/Tb5NaWz0+6ENnrreVdgkqYtilneMrgh3QbOowQG6gg6U8T3GuR6LDcSWdjbWSzbbZtjMSxVVz1CgL265rXnsorm7tLl92+1ZnjweMspU5/AmoL/SIr64iuVnntbqNSiz27ANtPJU5BBGQDyPpQBzkOsXy/bNPaeR30/WrayFw2N00TrE+GwAM4k2n1xnvWvdX1zH450qwWUi1m067mkjwMM6SW4U+vAdvzqQ+GdObR5NNcTPHJN9oaV5C0pm3BxJuP8AEGAI7DAAwBiiz8OWtrq0eqPcXlzfRwvAJbibd8jlCRtGFHKL0A70AU/CkWoXek2Gpahq088jxlvKVFSMg5xkYJJAxznr2HSn+Of+RM1H/dT/ANDWtjT7GLTbCCyg3eVCuxdxycVBrGkQ63p7WVxLNHCzAt5LBS2OxyDxn+VAGbrmjajLrlhrukvateWcE1v9nu9wjkSTaeGUEo2UXnB4JGKqz6xcXNvqun6npQstRTTHmDJMssciEEHa2A3Ddio6itW68Px3MkE41DUYbmGPy/PhuNpdc5+dcbW+pXjJx1p8Og2sUN0sktxcS3URhlnnk3OUwRgcYA5PAAoA5q1i1LxJo2g27aPcadDazW1w9zcTRbisYDDyxGz53EBTnbwW+h7mora3S0tIbaPPlxIsa5OTgDAqWgAooooAo6veXNjp0k1paPdTghUjQZ6nGT7DrWZobpDcv5lnqLXl0cz3dxbhQcDgcH5VHQAfzJNdDRWinaLjYlxvK4UUUVmUFFFFABVPUGn2QwW5KNPKI2kH/LNcFiR74XA9CQecVcrF8R6kdNisDGjtPPdeTEEiaTDGOQliq8kBVZsd8Y70AF9rOj+HI1tnO2QgssEKl3bPVj6ZOfmYjJzzV3StUg1jT1vLdZFjZmXbIuGBBwc/lXnniOSwl1WJtPuI7hPIxJKjhmaQOwbcR/ECMEHpjHGKqRavdf2GdIRGhg82RpWyMzAsSAMdF9e55HTruqN4prqdKoc0U1uza8UeJF1Tdp9mQbJWHmS/89iDkbf9kEde+PTrH4Z8RDSG+y3P/Hk7E7scxMep9x6+lc/S10eyjy8p1ewjycp6prGqxaRpEuoPG0yJsAWMjLFmCjBPHVhXF6t8WbPR442n0e7JkyFCyJ1Hrzx1rGn1a7Tw9NpIjaeCSSExgEAxYlVj1/hwCcdu3pXE+O/9TZf7z/0qaGGUpcsyMPhIynyzN3UfjPrGpyx22nWcOnxyMqs+7zZBk84JAH6Zr3G3torSEQwJtQc9ckk9SSeST1JPJr5Cs+L63z/z0X+Yr68S7tpHCJcQsx6BXBJp42jClyqCHmFCFHlUF3JqKKK4TzgooooAKKKKACiiigAooooAK4u68Pare6N42tDFDFJrfmG1JlyATbRwgNgccoT34NdpRQBk3enzza1o90m3yrQSiXnn5kAGPxrL/sXUJ9BsbGW3hEumSRtHmY7LkKCp5AyuVP4GuqooA5a90ae/0e/hh0uKzuJljRWa43swD7iD6D0579BWvf2U1xq2lXMe3y7WWR5MnnBjZRj8SK0qKAOZ1HSdUMmpzWgVhcXcEvlCYxmaJUVXTcPuk4P1xg4BzWcnhi/Nx4gubews7Jb7T4ILeATdZI2mY+YQuBneoyN34129FAGLLZ3eoalYXU8AgSOG4ilTzAxG/ZjBH+6apWun6rJY6dpV1awxRWMsRNyk24SpEcptXGQTtXIPTJwT36egkAZJwKAOcm0W7k8NaxYAJ593PO8fzcYdyRk/Q1S17Q77UU1iB9MttRN1Gy2stzPtjiUoBsK4ODuBOQDnPJFddvUnG4fnTqAMLTdIubTxLd6jIY/Jm060tVAPzb42mLZ9v3i4/Gn6xYX51Gy1XS/Je5tleKSCd2RZoXKlgGAOGBRSCQe443ZG1RQBxs+gane6nc6jYQQ6JO+n3Vurhg7tPKUKysF4+UoepJ+Y1JY6Fcf27pV+dIgs/siSpLKZxLK+5QOuMkZA6nPqBiuuooA5GTRNVuPDUWnNb2y3NhOksBedjFcBHJAJA3JuX2O0nowHNxdH+2Wt/G+lRWMk9s0CymfzHOf5AHBHOfYV0VFAHKP4f1G4s9PeZoFvJJCdSCtlWR3V3VTjnGxVHHTNR6voV/fXWsR3FlBqUF6m21aeUBLZDGFKbCDk7tzZA53YJGK6+igDkNX026Sy0G0t50hvHT7DNgZLQtH+828jBUqrA+2O9dbFGkMSRRqFjRQqqOgA6ClKqWDFQWHQ45FLQAUUUUAFFFFABRRRQAUUUUAFFFFAFa9vrbT4RLcybFZgiAAszseiqByT7Cq8WuadJbXVw1wII7Rd9x9oUxGFcZ3MGAIGATnpxWb4ntZnu9KvUa7EFtK/nG0G6RA67QwGDkDvgE4JrLvbSK+0fVLnTjqepXHlRArcxlPORJN5jXcq5JAYf8C560Ab9j4n0vULqO2ha6SWVmWMT2c0Qk2jcSpdQCMc5HBq8mo2j2txcrLmG3Z1lbaflKEhu3bBrn5NXg1XXvD720N2qebKxae3eHB8l/lw4Bz+HFVZr82Gl65pj2N/LezTXTQRQ2zv5qvuZSHxtA5xkkc8dcUAdHFqKT6nHHHcwtA9mLhY9jbyC3D56bcdsZqlD4z0G4e2EV6zRXIQw3Igk8hi5AVfN27NxJA25zz0qnpdtcRatZPJDKiLoaRszIQA4YfKT6+1YGiXC6t8K9B0SziujeTafaJk27qkYAQlyxAGBgkEHnjFAHYX/inSNNuJ7aaeWS5t1Vpbe3t5JpFVujbEUnHXnGOKhHjTQGNoUvjJDdFVjuY4XaDLY2hpQuxSSQAGI5OKl0yGVPE+uyvG6xyfZ9jlSA2EOcHvisQ2Vyfhh9lNtMbj/nl5Z3/67PTr05oA6S713T7O7a0kkkkuEQSSRQQvK0aHOGYKDtBwcZ64PpTJPEWkx29nP9tR4rxDJbNEDJ5yjH3doOfvDiudkgk03xLrUt/eatb215LFPby2qF4yPKSMpwrEMChPOB8/Herum2kcd5oD2UF4LRYLpt1zEyOpdkPzggFSTkgEA+1ACap43sofB2r65poeeTT0ffbzQSROsgXcFdGUMmQQckDgg1qt4h06O0iuJZJYxLIIY0e3kV5JNu7aiFdzcAngHgH0rmvEmk3uoaZ46trW1keW8sVSAbcea3kkYU9znArR1G507WNMsbvzdWs2hkLRXUFrIkkDlCDuRkORhiPmUjPXkUAb9lqFvqCSNB5o8ttjrLE0bKcA9GAPQirVYnhy41G4S8N5M9xbrKPslxJbmB5E2gncvHRsgHAyO3GTt0AFFFFABRRRQAUUUUAFUdSVlNpciIyLbT+Y4UZYKUZCVHcjdnHXGcZOBV6igDznxjLBca3bz27xyRyWikSRkEN8zdx1rBre8aW8MPiNXihjR5bZWkZVALnc3J9TWDXoUvgR6lH+GgooorQ0CuQ8d/6iy/3n/pXX1yHjv/U2X+8/9K0o/Gjah/ERyFmM31uCP+Wi/wAxX1ZqdpbRLaPHbxIwu4sMqAH71fNXhPw1f+JtbhtbKLKqwaWRvuooPJNfTkWiaXBMk0Wn2ySIcqwjGVPqKwzCScoo581knOKT1RfooorzjyQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACsLxkA3hHUQ0fmAxjKcfN8w454rdrO17T5tU0S6sreRI5ZVARpASoIIPOPpSkrpmlGSjUi30aMLTrDTo9QgeLwEbJw4K3Pk2o8o+uVct+Qrrqy4f7f89PP/ALN8rcN+zzN2O+M961KUVYuvUc2m/wA2/wA2woooqjAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAK1xYxXN3aXMm7zLVmePB4yylTn8Cas0UUAIQGUg9CMVV0zTrfSNKtNNtAwtrSFIIgxyQqgAZPfgVbooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiioLxrhLOV7SNJLhVJRHOAx9M9s0AcP44ilOuQSLBM6G2A3JGzDO5uMge4rm/Lm/59rj/vy/8AhXpsWuJetp62KeY10DI4fjyY14Yt6Hd8uPXPoafF4h0ma8S1jvY2keVoUODteRc7kVsbWYbWyoORtPoa3jXcVax0wxLjFRseX+XN/wA+1x/35f8Awo8ub/n2uP8Avy/+FesNqdktpPdtOogt2ZJXwcKVOGH4GobjXtLtbxrSa9jS5VlUxHO7LdOPT37d6r6y+xX1t9jy3y5v+fa4/wC/L/4Vk6r4X1LxRqOnWFpbyoCzmSWSNlWNeOSSK9i8T6rcaH4a1DVraGKdrKB7ho5HKhlRSxAIB54qG71i/i1DTtLgtbV766gkndpJykaIm0HbwWY5deMAAZJPQFrFSWqRUcZKLulqS+GvDVh4X0lLGxj95JSPmkb1P+HatisK81TVtP0m6ubuytBNHLGkPlzsySB2VcnKgqQWPHPTrzgWLPUbw6p/Z2oW0McxhM6PBKXRlDBSDkAg8j161zNtu7OOTcnd7mrRRRSEFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFZuv6uNB0O71V7aS4itImmlSNlDBFUsSMkZ6dKANKiqg1GCO2WW8kitGKb2SWVRtHqTnGORzUN7rmnWH2E3F3CqXshjhcyKFYhGfOSeRhT0z1FAGjRVabUbK3SJ57y3iWbHls8qqHz6ZPNPmu7a33edcRR7V3NvcDAzjJz2oAmoqs2o2KSrE15brI7lFQyqCWHUAZ6+1LPf2dtKsVxdwRSNyqSSBSe3AJoAz9K0xbPVNbuFhMf2u5V1fP3h5SZx6Ddv49ST3rDhsb1PD+j+HFsbrz7Oe2El2+NgSF1cybww3FgmMDJy/Ixmulm1mwt9UXT5rmOOdo/MAd1AxkADk5yc8VLFfRtBNNMUgjikZGZpFIwpxkkHA+h5HegDk7yPUE0bXdITSbyWae4mkikQL5bo7bgwYntnBHXI6Y5rd060mh8S61cyRFYp/IEbn+LahB/I1pJe2stutxHcwvAxAWRZAVJJwMHp14pIL+zukke3u4JViOJGjkDBD746UAZPjW2uL7wTrVjaW8k9zd2U0EUaAZLsjAdegz3pmsLa3cdnHqHh64vrfaXWVYldrd8Y6Z3gkE8qD3zjvsQ6haXSu1rdQT7BlhFIGx9cVBoeqLrmgafqyRNEl7bR3CxsclQ6hsE/jQBzcmkX82ianbxRXaWc1xbm0tppS0saq6F2ySSAcEgZyMds101lpNrYTSTp5stxIoRpp5WkcqOQMk8DnoKq/261y8w0zT5r+OCRonlSRETepwygsRkggg9gRj1qzDq0H2CG6vQdOMuR5N46I6kHBBwSD+BIoAv0Vn3uuadp5svtN1Ei3shjhcyKFJCM+ck9MKemeoqebUbK3SJ57y3iWbHls8qqHz6ZPNAFmimGaIO6GRNyKGYbhlQc4J9BwfyppuIAEJmjAdSyncPmUckj1FAEtFVodRsbhJHgvLeVIxl2SVWCj1ODxUzTRKqM0qBXICEsMMT0A9aAH0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFc749y/gHX4UR3ln0+eKJEUszuY2AAA7muiooA5xrS3vvFmn3UlqkyJpsuySSLO0l4+hI4JA/SqEcMdta20lxbkW1trVwT+6yI4280A4xwuWX2rsqKAOPmZIdbvprqYQWlzDELZ3tfMR4tuCmccfMSdp67hUmn6PaSa3Ck8H2uCHSoUikuoefvv2YcHGO2a6yigDz7UtKz4M8byQWH+nSyXbwskP713EfyFSBkkEDBHoMVe1i8abUtRsbyRreMWqCFI7EyyXIYHPzkMCA3G0DIxknDCuzooA4+wMNteaDJfwsGk0lY/MeFm/eAx8FscNzwDyecdDULxeTHb3V5DM1lb65cSzKsbNwxkVHKjqoZlOcEDhu2R21FAHn2t2Ueo22oTWFmZLG71PS2YJEdszLcR+a+McjYEBbp8p9K1dQhfTvEN/c2GnJITo/+rSL5ZWVztU464DHj3OOtdZRQBxVm6z+KtPmtr2e7Q2VwshSz8qEcx4G4KOf9ksSPStbwNDLb+AfD0E8TxSx6bbq8bqVZSI1yCD0Nb9FAHI2F8uk6dNo+oTz6dcwzSNHcJEXWZGkZlZGKFWYjqvJBz7ExpqV4bTTf7Tke3Egn3Xk1oDISJMIgXbhSyc8rzjgV2VFAHCaaiQ6RZT3KXEttb6zcMz3FsUZY2MoBKbRtXLL2A6H3q3MyQ63fTXUwgtLmGIWzva+YjxbcFM44+Yk7T13CuwooA466spLYaXa2v2qeG/tBp7ymNgVQEMGbj5cJ5vXHOB1NEKXto2ooti040m0kgtUdcrMHO4AeuEWNSOp5FdjRQBxdi0d14s06SG8mvIms7hJdtmI4OseBu29f9kse/FWNGhnl1gaXNE/2bQuI5CQVlZwfL98pGefdh+HWVBbWcNp5xiBzNK0shJyWY//AFgB9AKAJ6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD/9k=</xsl:attribute>
        </xsl:copy>
    </xsl:template>-->

    <xsl:template match="a[@href]">
        <xsl:variable name="parentFilename" select="pfn:generateFileName(ancestor::chapter/section)"/>
        <xsl:variable name="href" select="@href"/>
        <xsl:variable name="hrefFilename"
            select="pfn:generateFileName($chapters/(chapter[.//*[@id = replace($href, '^#', '')]])[1]/section)"/>
        <a>
            <xsl:apply-templates select="@*"/>
            <xsl:attribute name="href">
                <xsl:value-of
                    select="
                        if ($parentFilename = $hrefFilename or not(starts-with($href, '#'))) then
                            $href
                        else
                            concat($hrefFilename, '.xhtml', $href)"
                />
            </xsl:attribute>
            <xsl:copy-of select="node()"/>
        </a>
    </xsl:template>

    <xsl:template match="@shape | @name | hr[matches(@style, 'page-break')]"/>


    <!-- functions -->
    <xsl:function name="pfn:generateChapterID">
        <xsl:param name="section"/>
        <xsl:variable name="chapterNumber"
            select="count($section/preceding::section[@epub:type = 'chapter']) + 1"/>
        <xsl:variable name="subchapterNumber">
            <xsl:value-of
                select="
                    $chapterNumber,
                    for $i in $section/ancestor-or-self::section[@epub:type = 'subchapter']
                    return
                        count($i | $i/preceding-sibling::section)"
                separator="."/>
        </xsl:variable>
        <xsl:value-of select="concat('c', $subchapterNumber)"/>
    </xsl:function>

    <xsl:function name="pfn:generateFileName">
        <xsl:param name="section"/>
        <xsl:variable name="chapter" select="$section/parent::chapter"/>
        <xsl:variable name="name"
            select="replace(replace(replace(lower-case($section/h1[1]), '[^(a-z|\s)]', ''), '^\s+', ''), '\s+', '-')"/>
        <xsl:value-of
            select="
                format-number(count($chapter/preceding-sibling::chapter) + 1, '000'),
                $name[. != '']"
            separator="-"/>
    </xsl:function>

    <xsl:function name="pfn:generateItemID">
        <xsl:param name="section"/>
        <xsl:value-of select="concat('id', replace(pfn:generateFileName($section), '-', ''))"/>
    </xsl:function>



</xsl:stylesheet>
